### ISSUE TITLE
Agenda: July 13 Azure Functions and Go

### ISSUE THREAD

**Issue by iennae** [osscda/lets-go-stream#4]
# Last Week

In the July 6 episode of Let's Go, we started out with remote pairing, and brought up VS Live Share. We discovered that doing this and remote streaming is resource intensive which leads to significant lag. We might revisit how to do this better by separating out streaming versus compute system.

We started talking about testing and dove into linting first. We learned about revive, a replacement for go linter with a bit more configuration from a viewer as well as a sample problem to lint: 

https://gist.github.com/aw-was-here/5b1c24646aa4c937be049d8461da248f

We also learned about the snitch tool to improve your TDD cycle:
https://github.com/axcdnt/snitch

We talked about a challenge of recommended patterns changing and linting not catching and cleaning up those changes automatically. 

We briefly talked about table tests, and finished with an intro to unit tests. In the next testing session, we'll start with unit tests. 

# This Week 

Azure Functions and Go with Aaron Wislang (@asw101)

* What is serverless? 
* Why serverless is an interesting solution? 
* Is there a difference in writing go for serverless versus for compute you manage?
* What's a "Function" (Azure Functions) and how is it serverless?
* Let's write a sample function.

**Comment by arschles** [comment]
cc/ @asw101
